apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt"
  name: ingress
  namespace: default
spec:
  tls:
  - hosts:
    - tom-preston.co.uk
    - profile.tom-preston.co.uk
    secretName: tls-secret
  rules:
    - host: tom-preston.co.uk
      http:
        paths:
          - backend:
              service:
                name: profile-svc
                port:
                  number: 80
            path: /
            pathType: Prefix
    - host: profile.tom-preston.co.uk
      http:
        paths:
          - backend:
              service:
                name: profile-svc
                port:
                  number: 80
            path: /
            pathType: Prefix
